# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0-266-gb1862bc
_src_path: https://github.com/cetmix/cetmix-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
github_odoo_ee: false
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 14.0
org_name: Cetmix
org_slug: cetmix
rebel_module_groups: []
repo_description: Cetmix Tower
repo_name: Odoo bases server management tool
repo_slug: cetmix-tower
repo_website: https://cetmix.com
use_pyproject_toml: false
use_ruff: true

